/*
 * File: app/store/MyOrderedQuestStore.js
 *
 * This file was generated by Sencha Architect version 4.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.store.MyOrderedQuestStore', {
    extend: 'Ext.data.ChainedStore',

    requires: [
        'Ext.util.Filter'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyOrderedQuestStore',
            source: 'QuestStore',
            filters: {
                filterFn: function(item) {
                    var requester = item.data.requester;

                    if(requester == "a"){
                        return true;
                    }else{
                        return false;
                    }
                }
            }
        }, cfg)]);
    }
});