/*
 * File: app/store/QuestStore.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.store.QuestStore', {
    extend: 'Ext.data.Store',
    alias: 'store.queststore',

    requires: [
        'QuickStart.model.Quest'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'QuestStore',
            model: 'QuickStart.model.Quest',
            data: [
                {
                    requester: 'a',
                    missionContent: 'sequi',
                    compensation: 60,
                    number: 'officiis',
                    acceptance: true,
                    contractor: 'sit',
                    complete: false
                },
                {
                    requester: 'ut',
                    missionContent: 'ipsum',
                    compensation: 634,
                    number: 'molestias',
                    acceptance: true,
                    contractor: 'a',
                    complete: true
                },
                {
                    requester: 'a',
                    missionContent: 'numquam',
                    compensation: 703,
                    number: 'rerum',
                    acceptance: true,
                    contractor: 'a',
                    complete: true
                },
                {
                    requester: 'vero',
                    missionContent: 'reprehenderit',
                    compensation: 962,
                    number: 'recusandae',
                    acceptance: false,
                    contractor: 'officia',
                    complete: false
                },
                {
                    requester: 'possimus',
                    missionContent: 'sunt',
                    compensation: 883,
                    number: 'quia',
                    acceptance: false,
                    contractor: 'nisi',
                    complete: false
                },
                {
                    requester: 'suscipit',
                    missionContent: 'eum',
                    compensation: 679,
                    number: 'molestiae',
                    acceptance: false,
                    contractor: 'consequatur',
                    complete: false
                },
                {
                    requester: 'rerum',
                    missionContent: 'eveniet',
                    compensation: 513,
                    number: 'consequuntur',
                    acceptance: true,
                    contractor: 'nihil',
                    complete: false
                },
                {
                    requester: 'in',
                    missionContent: 'voluptas',
                    compensation: 497,
                    number: 'in',
                    acceptance: true,
                    contractor: 'dignissimos',
                    complete: false
                },
                {
                    requester: 'expedita',
                    missionContent: 'ducimus',
                    compensation: 734,
                    number: 'et',
                    acceptance: true,
                    contractor: 'et',
                    complete: false
                },
                {
                    requester: 'quas',
                    missionContent: 'vel',
                    compensation: 711,
                    number: 'ut',
                    acceptance: false,
                    contractor: 'et',
                    complete: true
                }
            ]
        }, cfg)]);
    }
});