/*
 * File: app/store/QuestStore.js
 *
 * This file was generated by Sencha Architect version 4.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.store.QuestStore', {
    extend: 'Ext.data.Store',
    alias: 'store.queststore',

    requires: [
        'QuickStart.model.Quest'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'QuestStore',
            model: 'QuickStart.model.Quest',
            data: [
                {
                    Name: 'accusamus',
                    Items: 'itaque',
                    Reward: 753
                },
                {
                    Name: 'ad',
                    Items: 'aliquid',
                    Reward: 668
                },
                {
                    Name: 'optio',
                    Items: 'numquam',
                    Reward: 518
                },
                {
                    Name: 'consequatur',
                    Items: 'totam',
                    Reward: 110
                },
                {
                    Name: 'eveniet',
                    Items: 'placeat',
                    Reward: 740
                }
            ]
        }, cfg)]);
    }
});