/*
 * File: app/view/GroupPopup.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.view.GroupPopup', {
    extend: 'Ext.form.Panel',
    alias: 'widget.grouppopup',

    requires: [
        'QuickStart.view.QuestAcceptPopupViewModel2',
        'QuickStart.view.QuestAcceptPopupViewController2',
        'Ext.field.Text',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        floating: true
    },

    controller: 'grouppopup',
    viewModel: {
        type: 'grouppopup'
    },
    width: 376,
    centered: true,
    modal: true,
    title: '確認',

    items: [
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'container',
                    height: 41,
                    html: '以下の共同購入に参加しますか？<br>目標人数に達したら、leafが提案者に振り込まれます。',
                    margin: 10
                },
                {
                    xtype: 'textfield',
                    bind: '{quest.requester}',
                    name: 'name',
                    margin: '0 10 0 10',
                    label: '提案者',
                    clearable: false,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    bind: '{quest.wish}',
                    name: 'item',
                    margin: '0 10 0 10',
                    label: '目的',
                    clearable: false,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    bind: '{quest.perchase}',
                    name: 'reward',
                    margin: '0 10 0 10',
                    label: '参加費',
                    clearable: false,
                    editable: false
                },
                {
                    xtype: 'toolbar',
                    docked: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'x-fa fa-check',
                            text: '受注',
                            listeners: {
                                tap: 'submitUpdate'
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'x-fa fa-close',
                            text: 'キャンセル',
                            listeners: {
                                tap: 'cancelUpdate'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                initialize: 'onContainerInitialize'
            }
        },
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'container',
                    height: 40,
                    html: '以下の共同購入の募集を停止しますか？',
                    margin: 10
                },
                {
                    xtype: 'textfield',
                    bind: '{quest.wish}',
                    name: 'wish',
                    margin: '0 10 0 10',
                    label: '目的',
                    clearable: false,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    bind: '{quest.price}',
                    name: 'price',
                    margin: '0 10 0 10',
                    label: '目標金額'
                },
                {
                    xtype: 'textfield',
                    bind: '{quest.fund}',
                    name: 'fund',
                    margin: '0 10 0 10',
                    label: '募集人数',
                    clearable: false,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    bind: '{quest.contructores}',
                    name: 'contructores',
                    margin: '0 10 0 10',
                    label: '参加者'
                },
                {
                    xtype: 'toolbar',
                    docked: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'x-fa fa-check',
                            text: '取り消し',
                            listeners: {
                                tap: 'submitUpdate1'
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'x-fa fa-close',
                            text: 'キャンセル',
                            listeners: {
                                tap: 'cancelUpdate1'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                initialize: 'onContainerInitialize1'
            }
        }
    ]

});