/*
 * File: app/view/GroupPurchase.js
 *
 * This file was generated by Sencha Architect version 4.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.view.GroupPurchase', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.grouppurchase',

    requires: [
        'QuickStart.view.GroupPurchaseViewModel',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'grouppurchase'
    },
    height: '100%',
    width: '100%',
    store: 'GroupPerchaseStore',
    title: '共同購入参加',

    columns: [
        {
            xtype: 'gridcolumn',
            flex: '1',
            width: 70,
            dataIndex: 'requester',
            text: '依頼者'
        },
        {
            xtype: 'gridcolumn',
            flex: '1',
            width: 89,
            dataIndex: 'number',
            text: '目的'
        },
        {
            xtype: 'gridcolumn',
            flex: '1',
            width: 89,
            dataIndex: 'price',
            text: '目標金額'
        },
        {
            xtype: 'gridcolumn',
            flex: '1',
            width: 70,
            dataIndex: 'fund',
            text: '目標人数'
        },
        {
            xtype: 'gridcolumn',
            flex: '1',
            width: 80,
            dataIndex: 'numberOfContractors',
            text: '現在人数'
        }
    ]

});