/*
 * File: app/view/loginViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.view.loginViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.login',

    onButtonTap: function(button, e, eOpts) {
        var store = Ext.getStore('UserDataStore');
        var queststore = Ext.getStore('QuestStore');
        var leafstore = Ext.getStore('LeafStore');
        var view = this;
        Ext.Ajax.request({
            url : 'http://52.199.251.125:4000/users', // url : this.getUrl(),
            method : "POST",
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            params : {'username': 'jim','orgName': 'org1'},
            useDefaultXhrHeader : false,

            success : function(response) {
                var jsonData = response.responseText;
                var data = JSON.parse(jsonData);
                var token = data['token'];
                var loadData = {"username":"a","token": token};
                store.loadData([loadData],false);
                var authorization = 'Bearer '+token;
                Ext.Ajax.request({
                    url : 'http://52.199.251.125:4000/channels/mychannel/chaincodes/skillgroup_cc2?peer=peer1&fcn=query&args=%5B%22a%22%5D', // url : this.getUrl(),
                    method : "GET",
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': authorization
                    },

                    success : function(response) {
                        var jsonData = response.responseText;
                        var loadData = JSON.parse(jsonData);
                        queststore.setData(loadData);
                        console.log(queststore.getData());


                        Ext.Ajax.request({
                            url : 'http://52.199.251.125:4000/channels/mychannel/chaincodes/skillgroup_cc1?peer=peer1&fcn=query&args=%5B%22a%22%5D', // url : this.getUrl(),
                            method : "GET",
                            headers: {
                                'Content-Type': 'application/json',
                                'Authorization': authorization
                            },

                            success : function(response) {
                                var jsonLeafData = response.responseText;
                                console.log(jsonLeafData);
                                var loadLeafData = JSON.parse(jsonLeafData);
                                leafstore.loadData([loadLeafData],false);
                                console.log(leafstore.getData());
                                Ext.Viewport.remove(Ext.Viewport.getActiveItem(), true);
                                Ext.Viewport.setActiveItem({
                                    xtype: "basemenu"
                                });
                            },
                            failure : function(response) {
                                // Ext.Msg.alert('Error', '通信失敗');
                            }
                        });
                    },
                    failure : function(response) {
                        // Ext.Msg.alert('Error', '通信失敗');
                    }});
                },
                failure : function(response) {
                    // Ext.Msg.alert('Error', '通信失敗');
                }});
    }

});