/*
 * File: app/view/Menu.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.view.Menu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.menu',

    requires: [
        'QuickStart.view.MenuViewModel',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'menu'
    },
    width: 200,

    items: [
        {
            xtype: 'menuitem',
            href: '#top',
            text: 'TOP'
        },
        {
            xtype: 'menuitem',
            href: '#order',
            text: 'クエスト依頼'
        },
        {
            xtype: 'menuitem',
            href: '#ordered',
            text: '依頼済みクエスト一覧'
        },
        {
            xtype: 'menuitem',
            href: '#accept',
            text: '受注可能クエスト一覧'
        },
        {
            xtype: 'menuitem',
            href: '#accepted',
            text: '受注済みクエスト一覧'
        },
        {
            xtype: 'menuitem',
            href: '#group',
            text: '共同購入一覧'
        },
        {
            xtype: 'menuitem',
            href: '#groupperchase',
            text: '共同購入募集'
        }
    ]

});