/*
 * File: app/view/order.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.view.order', {
    extend: 'Ext.form.Panel',
    alias: 'widget.order',

    requires: [
        'QuickStart.view.orderViewModel',
        'QuickStart.view.orderViewController',
        'Ext.form.FieldSet',
        'Ext.field.Number',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    controller: 'order',
    viewModel: {
        type: 'order'
    },
    itemId: 'order',
    title: 'クエスト依頼',
    titleAlign: 'center',

    items: [
        {
            xtype: 'container',
            height: 24,
            html: '以下の内容でクエスト依頼をします。',
            margin: 10
        },
        {
            xtype: 'fieldset',
            items: [
                {
                    xtype: 'textfield',
                    name: 'missioncontent',
                    label: '依頼内容',
                    requiredMessage: '入力してください'
                },
                {
                    xtype: 'numberfield',
                    name: 'compensation',
                    label: '報酬',
                    requiredMessage: '入力してください'
                }
            ]
        },
        {
            xtype: 'container',
            height: 57,
            items: [
                {
                    xtype: 'toolbar',
                    height: 46,
                    docked: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'x-fa fa-check',
                            text: '依頼',
                            listeners: {
                                tap: 'submitUpdate'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});