/*
 * File: app/view/ordered.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.view.ordered', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.ordered',

    requires: [
        'QuickStart.view.orderedViewModel',
        'QuickStart.view.orderedViewController',
        'Ext.grid.column.Boolean'
    ],

    config: {
        iconCls: 'x-fa fa-tasks'
    },

    controller: 'ordered',
    viewModel: {
        type: 'ordered'
    },
    height: '100%',
    itemId: 'ordered',
    width: '100%',
    store: 'MyOrderedQuestStore',
    title: '依頼済クエスト一覧',

    columns: [
        {
            xtype: 'booleancolumn',
            flex: 1,
            width: 100,
            dataIndex: 'acceptance',
            text: '受注済み'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            width: 100,
            dataIndex: 'contractor',
            text: '受注者'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            width: 100,
            dataIndex: 'compensation',
            text: '報酬'
        },
        {
            xtype: 'gridcolumn',
            flex: 1,
            width: 100,
            dataIndex: 'missionContent',
            text: '依頼内容'
        }
    ],
    listeners: {
        childtap: 'onMygridChildtap'
    }

});