/*
 * File: app/view/QuestAcceptPopup.js
 *
 * This file was generated by Sencha Architect version 4.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.view.QuestAcceptPopup', {
    extend: 'Ext.form.Panel',
    alias: 'widget.questacceptpopup',

    requires: [
        'QuickStart.view.QuestAcceptPopupViewModel',
        'QuickStart.view.QuestAcceptPopupViewController',
        'Ext.field.Text',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        floating: true
    },

    controller: 'questacceptpopup',
    viewModel: {
        type: 'questacceptpopup'
    },
    centered: true,
    modal: true,
    title: '受注確認',

    items: [
        {
            xtype: 'container',
            height: 27,
            html: '以下のクエストを受注しますか？',
            margin: 10
        },
        {
            xtype: 'textfield',
            bind: '{quest.requester}',
            name: 'name',
            label: '依頼者',
            clearable: false,
            editable: false
        },
        {
            xtype: 'textfield',
            bind: '{quest.missionContent}',
            name: 'item',
            label: '依頼内容',
            clearable: false,
            editable: false
        },
        {
            xtype: 'textfield',
            bind: '{quest.compensation}',
            name: 'reward',
            label: '報酬',
            clearable: false,
            editable: false
        },
        {
            xtype: 'toolbar',
            docked: 'bottom',
            items: [
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-check',
                    text: '受注',
                    listeners: {
                        tap: 'submitUpdate'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-close',
                    text: 'キャンセル',
                    listeners: {
                        tap: 'cancelUpdate'
                    }
                }
            ]
        }
    ]

});