/*
 * File: app/view/QuestCompletePopup.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.view.QuestCompletePopup', {
    extend: 'Ext.form.Panel',
    alias: 'widget.questcompletepopup',

    requires: [
        'QuickStart.view.PopupFormViewModel1',
        'QuickStart.view.PopupFormViewController1',
        'Ext.field.Text',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        floating: true
    },

    controller: 'questcompletepopup',
    viewModel: {
        type: 'questcompletepopup'
    },
    centered: true,
    modal: true,
    title: '依頼済クエスト確認',

    items: [
        {
            xtype: 'container',
            height: 27,
            html: '以下のクエストを完了し、報酬を支払いますか？',
            margin: 10,
            listeners: {
                initialize: 'onContainerInitialize'
            }
        },
        {
            xtype: 'container',
            height: 27,
            html: '以下のクエストを削除しますか？',
            margin: 10,
            listeners: {
                initialize: 'onContainerInitialize1'
            }
        },
        {
            xtype: 'textfield',
            bind: '{quest.contractor}',
            name: 'name',
            margin: '0 10 0 10',
            label: '受注者',
            clearable: false,
            editable: false
        },
        {
            xtype: 'textfield',
            bind: '{quest.missionContent}',
            name: 'item',
            margin: '0 10 0 10',
            label: '依頼内容',
            clearable: false,
            editable: false
        },
        {
            xtype: 'textfield',
            bind: '{quest.compensation}',
            name: 'reward',
            margin: '0 10 0 10',
            label: '報酬',
            clearable: false,
            editable: false
        },
        {
            xtype: 'toolbar',
            height: 41,
            docked: 'bottom',
            items: [
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-check',
                    text: '完了',
                    listeners: {
                        tap: 'submit',
                        initialize: 'onButtonInitialize'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-close',
                    text: '削除',
                    listeners: {
                        tap: 'delete',
                        initialize: 'onButtonInitialize1'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-close',
                    text: 'キャンセル',
                    listeners: {
                        tap: 'cancel'
                    }
                }
            ]
        }
    ]

});