/*
 * File: app/model/GroupPerchase.js
 *
 * This file was generated by Sencha Architect version 4.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.model.GroupPerchase', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Boolean'
    ],


    fields: [
        {
            name: 'number'
        },
        {
            name: 'requester'
        },
        {
            name: 'wish'
        },
        {
            name: 'price'
        },
        {
            name: 'contractores'
        },
        {
            name: 'fund'
        },
        {
            type: 'boolean',
            name: 'complete'
        },
        {
            mapping: function(data) {
                return data.contractores;
            },
            name: 'numberOfContractors'
        }
    ]

});