/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.controller.MyController', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.route.Route'
    ],

    routes: {
        'order': 'goOrder',
        'accept': 'goAccept',
        'accepted': 'goAccepted',
        'ordered': 'goOrdered',
        'top': 'goTop',
        'group': 'goGroup',
        'groupperchase': 'goGrouporder'
    },

    goOrder: function() {
        var maincontents = Ext.ComponentQuery.query('#maincontents')[0];
        maincontents.setActiveItem(0);
    },

    goAccept: function() {
        var maincontents = Ext.ComponentQuery.query('#maincontents')[0];
        maincontents.setActiveItem(2);
    },

    goAccepted: function() {
        var maincontents = Ext.ComponentQuery.query('#maincontents')[0];
        maincontents.setActiveItem(3);
    },

    goOrdered: function() {
        var maincontents = Ext.ComponentQuery.query('#maincontents')[0];
                maincontents.setActiveItem(1);
    },

    goTop: function() {
        var maincontents = Ext.ComponentQuery.query('#maincontents')[0];
                maincontents.setActiveItem(4);
    },

    goGroup: function() {
         var maincontents = Ext.ComponentQuery.query('#maincontents')[0];
                        maincontents.setActiveItem(5);
    },

    goGrouporder: function() {
        var maincontents = Ext.ComponentQuery.query('#maincontents')[0];
                                maincontents.setActiveItem(6);
    }

});